bullet proof release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -30,7 +30,14 @@ jobs:
         with:
           fetch-depth: '0'
           token: ${{ secrets.ECOTONE_BOT_TOKEN }}
-          
+
+      - name: Ensure ECOTONE_ENTERPRISE_PUBLIC_KEY secret exists
+        run: |
+          if [ -z "${{ secrets.ECOTONE_ENTERPRISE_PUBLIC_KEY }}" ]; then
+            echo "ECOTONE_ENTERPRISE_PUBLIC_KEY secret is missing"
+            exit 1
+          fi
+
       - name: Setup Git
         run: |
           git config user.name "Ecotone Framework Bot"
