test split testing

diff --git a/.github/workflows/split-testing.yml b/.github/workflows/split-testing.yml
--- a/.github/workflows/split-testing.yml
+++ b/.github/workflows/split-testing.yml
@@ -8,6 +8,124 @@ concurrency:
   group: split-tests-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
   cancel-in-progress: true
 
+# Define reusable configuration with YAML anchors
+# These are not jobs, just anchor definitions
+_services: &services
+  kafka:
+    image: bitnami/kafka:latest
+    options: >-
+      --env ALLOW_PLAINTEXT_LISTENER=yes
+      --env KAFKA_ENABLE_KRAFT=yes
+      --env KAFKA_CFG_NODE_ID=0
+      --env KAFKA_CFG_PROCESS_ROLES=controller,broker
+      --env KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
+      --env KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
+      --env KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
+      --env KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
+      --env KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
+      --health-cmd="kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list || exit 1"
+      --health-interval=10s
+      --health-timeout=5s
+      --health-retries=5
+    ports:
+      - 9092:9092
+  rabbitmq:
+    image: rabbitmq:3.11-management-alpine
+    env:
+      RABBITMQ_DEFAULT_USER: guest
+      RABBITMQ_DEFAULT_PASS: guest
+    ports:
+      - 5672:5672
+  mysql:
+    image: mysql:8.0
+    env:
+      MYSQL_ROOT_PASSWORD: "secret"
+      MYSQL_USER: "ecotone"
+      MYSQL_PASSWORD: "secret"
+      MYSQL_DATABASE: "ecotone"
+      DB_PORT: 3306
+    options: >-
+      --health-cmd="mysqladmin ping"
+      --health-interval=10s
+      --health-timeout=10s
+      --health-retries=5
+    ports:
+      - 3306:3306
+  postgres:
+    image: simplycodedsoftware/postgres:16.1
+    env:
+      POSTGRES_USER: ecotone
+      POSTGRES_PASSWORD: secret
+    options: >-
+      --health-cmd pg_isready
+      --health-interval 10s
+      --health-timeout 5s
+      --health-retries 5
+    ports:
+      - 5432:5432
+  localstack:
+    image: localstack/localstack:2.2.0
+    env:
+      SERVICES: 'sqs,sns'
+    ports:
+      - "4566:4566"
+      - "4510-4559:4510-4559"
+  redis:
+    image: redis:7-alpine
+    ports:
+      - '6379:6379'
+
+_env: &env
+  RABBIT_HOST: amqp://127.0.0.1:5672
+  SQS_DSN: sqs:?key=key&secret=secret&region=us-east-1&endpoint=http://127.0.0.1:4566&version=latest
+  REDIS_DSN: redis://127.0.0.1:6379
+  KAFKA_DSN: localhost:9092
+
+_steps: &steps
+  - uses: actions/checkout@v2
+
+  - name: Set Up PHP
+    uses: shivammathur/setup-php@v2
+    with:
+      php-version: ${{ matrix.php-version }}
+      extensions: grpc, rdkafka
+      coverage: none
+
+  - name: Install OpenSSH (For Kafka)
+    run: sudo apt-get update && sudo apt-get install -y --no-install-recommends openssh-client
+
+  - name: Enable merge-plugin
+    run: composer global config --no-interaction allow-plugins.wikimedia/composer-merge-plugin true && composer global require wikimedia/composer-merge-plugin
+    working-directory: ${{ matrix.package.directory }}
+
+  - name: Install dependencies
+    run: composer update --${{ matrix.stability }} --no-interaction
+    working-directory: ${{ matrix.package.directory }}
+    env:
+      COMPOSER_ROOT_VERSION: 'dev-main'
+
+  - name: Run tests on Postgres
+    run: composer tests:ci
+    working-directory: ${{ matrix.package.directory }}
+    env:
+      COMPOSER_ROOT_VERSION: 'dev-main'
+      DATABASE_DSN: pgsql://ecotone:secret@127.0.0.1:5432/ecotone
+      SECONDARY_DATABASE_DSN: mysql://ecotone:secret@127.0.0.1:3306/ecotone
+      APP_DB_HOST: 127.0.0.1
+      APP_DB_PORT: 5432
+      APP_DB_DRIVER: pdo_pgsql
+
+  - name: Run tests on Mysql
+    run: composer tests:ci
+    working-directory: ${{ matrix.package.directory }}
+    env:
+      COMPOSER_ROOT_VERSION: 'dev-main'
+      DATABASE_DSN: mysql://ecotone:secret@127.0.0.1:3306/ecotone
+      SECONDARY_DATABASE_DSN: pgsql://ecotone:secret@127.0.0.1:5432/ecotone
+      APP_DB_HOST: 127.0.0.1
+      APP_DB_PORT: 3306
+      APP_DB_DRIVER: pdo_mysql
+
 jobs:
   get_packages:
     name: Get packages
@@ -32,129 +150,36 @@ jobs:
     outputs:
       matrix: ${{ steps.get_json.outputs.json }}
 
-  split_testing:
-    name: Testing ${{ matrix.package.name }} separately (${{ matrix.stability }})
+  split_testing_php81_lowest:
+    name: Testing ${{ matrix.package.name }} separately on lowest dependencies
     needs: get_packages
     runs-on: ubuntu-latest
-
+    
+    services: *services
+    env: *env
+    
     strategy:
       fail-fast: true # Fail the entire workflow if any job fails
       matrix:
         package: ${{ fromJson(needs.get_packages.outputs.matrix) }}
-        stability: [ prefer-lowest, prefer-stable ]
-        php-versions: [ '8.1', '8.3' ]
+        php-version: [ '8.1' ]
+        stability: [ 'prefer-lowest' ]
+    
+    steps: *steps
 
-    services:
-      kafka:
-        image: bitnami/kafka:latest
-        options: >-
-          --env ALLOW_PLAINTEXT_LISTENER=yes
-          --env KAFKA_ENABLE_KRAFT=yes
-          --env KAFKA_CFG_NODE_ID=0
-          --env KAFKA_CFG_PROCESS_ROLES=controller,broker
-          --env KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
-          --env KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
-          --env KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
-          --env KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
-          --env KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
-          --health-cmd="kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list || exit 1"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
-        ports:
-          - 9092:9092
-      rabbitmq:
-        image: rabbitmq:3.11-management-alpine
-        env:
-          RABBITMQ_DEFAULT_USER: guest
-          RABBITMQ_DEFAULT_PASS: guest
-        ports:
-          - 5672:5672
-      mysql:
-        image: mysql:8.0
-        env:
-          MYSQL_ROOT_PASSWORD: "secret"
-          MYSQL_USER: "ecotone"
-          MYSQL_PASSWORD: "secret"
-          MYSQL_DATABASE: "ecotone"
-          DB_PORT: 3306
-        options: >-
-          --health-cmd="mysqladmin ping"
-          --health-interval=10s
-          --health-timeout=10s
-          --health-retries=5
-        ports:
-          - 3306:3306
-      postgres:
-        image: simplycodedsoftware/postgres:16.1
-        env:
-          POSTGRES_USER: ecotone
-          POSTGRES_PASSWORD: secret
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 5432:5432
-      localstack:
-        image: localstack/localstack:2.2.0
-        env:
-          SERVICES: 'sqs,sns'
-        ports:
-          - "4566:4566"
-          - "4510-4559:4510-4559"
-      redis:
-        image: redis:7-alpine
-        ports:
-          - '6379:6379'
-
-    env:
-      RABBIT_HOST: amqp://127.0.0.1:5672
-      SQS_DSN: sqs:?key=key&secret=secret&region=us-east-1&endpoint=http://127.0.0.1:4566&version=latest
-      REDIS_DSN: redis://127.0.0.1:6379
-      KAFKA_DSN: localhost:9092
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Set Up PHP
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ matrix.php-versions }}
-          extensions: grpc, rdkafka
-          coverage: none
-
-      - name: Install OpenSSH (For Kafka)
-        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends openssh-client
-
-      - name: Enable merge-plugin
-        run: composer global config --no-interaction allow-plugins.wikimedia/composer-merge-plugin true && composer global require wikimedia/composer-merge-plugin
-        working-directory: ${{ matrix.package.directory }}
-
-      - name: Install dependencies
-        run: composer update  --${{ matrix.stability }} --no-interaction
-        working-directory: ${{ matrix.package.directory }}
-        env:
-          COMPOSER_ROOT_VERSION: 'dev-main'
-
-      - name: Run tests on Postgres
-        run: composer tests:ci
-        working-directory: ${{ matrix.package.directory }}
-        env:
-          COMPOSER_ROOT_VERSION: 'dev-main'
-          DATABASE_DSN: pgsql://ecotone:secret@127.0.0.1:5432/ecotone
-          SECONDARY_DATABASE_DSN: mysql://ecotone:secret@127.0.0.1:3306/ecotone
-          APP_DB_HOST: 127.0.0.1
-          APP_DB_PORT: 5432
-          APP_DB_DRIVER: pdo_pgsql
-
-      - name: Run tests on Mysql
-        run: composer tests:ci
-        working-directory: ${{ matrix.package.directory }}
-        env:
-          COMPOSER_ROOT_VERSION: 'dev-main'
-          DATABASE_DSN: mysql://ecotone:secret@127.0.0.1:3306/ecotone
-          SECONDARY_DATABASE_DSN: pgsql://ecotone:secret@127.0.0.1:5432/ecotone
-          APP_DB_HOST: 127.0.0.1
-          APP_DB_PORT: 3306
-          APP_DB_DRIVER: pdo_mysql
+  split_testing_php_stable:
+    name: Testing ${{ matrix.package.name }} separately on stable dependencies
+    needs: get_packages
+    runs-on: ubuntu-latest
+    
+    services: *services
+    env: *env
+    
+    strategy:
+      fail-fast: true # Fail the entire workflow if any job fails
+      matrix:
+        package: ${{ fromJson(needs.get_packages.outputs.matrix) }}
+        php-version: [ '8.3' ]
+        stability: [ 'prefer-stable' ]
+    
+    steps: *steps
